name: Deploy Java

on:
  workflow_call:

jobs:
  reusable_workflow_deploy:
    name: Reusable
    runs-on: ubuntu-24.04
    container:
      image: maven:3.9.2
    env:
      PRJ_FULL_PATH: ${{ github.workspace }}/base-code
      ADM_FULL_PATH: ${{ github.workspace }}/devsecops-code
    steps:
      - name: Get Composite
        uses: actions/checkout@v4
        with:
          repository: Dumas-Carvalho/devsecops-workflows
          ref: main
          path: ${{ env.ADM_FULL_PATH }}

      - name: Run Composite
        uses: ./devsecops-code/actions/setup-java
        with:
          jdk_version: '17'

      - name: Deploy App
        run: |
          chmod +x scripts/deliver.sh
          ./scripts/deliver.sh
        working-directory: ${{ env.PRJ_FULL_PATH }}
