name: Test Java

on:
  workflow_call:

jobs:
  reusable_workflow_test:
    name: Reusable
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.2
    env:
      PRJ_FULL_PATH: ${{ github.workspace }}/base-code
      ADM_FULL_PATH: ${{ github.workspace }}/devsecops-code
    steps:
      - name: Get Composite
        uses: actions/checkout@v4
        with:
          repository: Dumas-Carvalho/devsecops-workflows
          ref: main
          path: ${{ env.ADM_FULL_PATH }}

      - id: setup_java
        uses: ./devsecops-code/actions/setup-java
        with:
          jdk_version: '17'

      - name: Unit Test
        run: |
          mvn -B clean test
        working-directory: ${{ env.PRJ_FULL_PATH }}
