name: Test Java

on:
  workflow_call:

jobs:
  reusable_workflow_test:
    name: Reusable
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Code
        uses: actions/checkout@v4

      - name: Get Composite
        uses: actions/checkout@v4
        with:
          repository: Dumas-Carvalho/devsecops-workflows
          ref: main
          path: .github/workflows

      - id: setup_java
        uses: ./.github/workflows/actions/setup-java
        with:
          jdk_version: '17'

      - name: Unit Tests
        run: mvn test
